### ISSUE TITLE
Bramble hollow issue

### ISSUE THREAD

**Issue by gratz-stack** [AquSG/TerRoguelike#3]
This boss may force player to take unavoidable damage with this pattern 
![fair](https://github.com/AquSG/TerRoguelike/assets/175079175/44057ab1-2a47-44f4-a982-4d5450945830)
also another issues is STILL NO PUBLIC DISCORD, people are itching to talk about how good the mod is

**Comment by AquSG** [comment]
If you bait both pillars to the same spot (preferably the top) then you can dodge it.

No discord because I do not have the free time to moderate it.
