### ISSUE TITLE
game crashing upon loading into the world

### ISSUE THREAD

**Issue by Kotabel** [AquSG/TerRoguelike#9]
tried pretty much everything, disabled all mods, disabled cloud saving, reinstalled the mod, uninstalled every other mod, enabled opengl and the result is still the same
[Natives.log](https://github.com/user-attachments/files/16317005/Natives.log)
[terrariasteamclient.log](https://github.com/user-attachments/files/16317006/terrariasteamclient.log)
[client.log](https://github.com/user-attachments/files/16317007/client.log)
[environment-client.log](https://github.com/user-attachments/files/16317008/environment-client.log)
[Launch.log](https://github.com/user-attachments/files/16317009/Launch.log)

**Comment by AquSG** [comment]
I really don't know what to say. I've seen probably one other person mention that they crash upon entering the world. It mentions a bunch of failed texture creation for water shader data and I don't touch that at all.

**Comment by Kotabel** [comment]
> I really don't know what to say. I've seen probably one other person mention that they crash upon entering the world. It mentions a bunch of failed texture creation for water shader data and I don't touch that at all.

i've tried asking about it on tmodloader discord but they told me to enable opengl and then just told me to contact the mod developer since it was only happening with 1 mod

**Comment by AquSG** [comment]
I mean, it's perfectly fair. Something is amiss if it is only happening with TerRoguelike enabled. But since there are no real leads and it is super uncommon, I have no clue what to do about it.

**Comment by Kotabel** [comment]
welp, hope you'll find a solution soon enough

**Comment by Kotabel** [comment]
Welp, hope you'll find something soon enough
